use_frameworks!

platform :ios, '9.0'

target 'BestBiometric_Example' do
  pod 'BestBiometric', :path => '../'

  target 'BestBiometric_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
